[config]

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.foot]
input_path = '~/.config/matugen/templates/foot-colors.ini'
output_path = '~/.config/foot/colors.ini'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.qutebrowser]
input_path = '~/.config/matugen/templates/qutebrowser-colors.py'
output_path = '~/.config/qutebrowser/colors.py'
